import './globals.css'
import type { Metadata } from 'next'
import { Inter, Anton } from 'next/font/google'
import { Header } from './components/Header'
import clsx from 'clsx'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anton',
})

const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anton',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${anton.variable}`}>
      <body
        className={clsx(
          inter.className,
          'text-typography-main flex min-h-screen flex-col justify-between leading-relaxed',
        )}
      >
        <Header className="bg-primary-accent min-w-screen fixed top-0 h-20 lg:h-40" />

        <main className="mt-20 flex min-h-screen flex-col items-center justify-between p-24 lg:mt-40">{children}</main>
      </body>
    </html>
  )
}
