import './globals.css'
import type { Metadata } from 'next'
import { Inter, Anton } from 'next/font/google'
import { Header } from './components/Header'
import clsx from 'clsx'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anton',
})

const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anton',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${anton.variable}`}>
      <body
        className={clsx(
          inter.className,
          'flex min-h-screen flex-col justify-between leading-relaxed text-typography-main',
        )}
      >
        <Header className="min-w-screen fixed top-0 z-50 bg-primary-accent" />
        <main className="mt-20 flex min-h-screen flex-col  p-8 text-center md:p-24 md:text-start lg:mt-40">
          {children}
        </main>
      </body>
    </html>
  )
}
